name: cortical-breach-detection
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pytorch=1.9.0
  - torchvision=0.10.0
  - cudatoolkit=11.1 # 11.2?
  - pycuda=2021.1
  - pip
  - pip:
      - -r requirements.txt
      - -e .
